### PR TITLE
Custom model

### PR DESCRIPTION
**Pull request by kristelizq**
Created customs models for lag and accumulation and modified the trough class accordingly:
-custom accu file: accumulation=coeff*1/ints(t)
-custom lag file: lag=intercept+linearCoeff*time+quadCoeff*time**2
-model names and custom models are mutually exclusive in trough class
-modified init file
-modified test file
-created notebook with example of how custom model works

### CODE REVIEW

**Comment by tmcclintock** [comment]
@kristelizq was this for issue #32? If so I apologize - I should have been more explicit by what I meant with custom models, and this PR is not what I meant.

What I meant was the following for just the lag model (it's the same idea for the accumulation model):

For the lag, the only function we *must* implement is `get_lag_at_t`. That is the **API** we have defined for the lag model requires us to implement that method. Suppose I wanted to try the following custom lag model:

```python
class MyLag(LagModel):
    # A "randomness" lag model  (note - this is a bad model)

    def __init__(self, foo: float):
        self.foo = foo

    def get_lag_at_t(self, time):
        # Returns a random number from U[0, 1] at each time times 'foo'
        return np.random.rand(len(time)) * self.foo

    @property
    def parameter_names(self):
        return ["foo"]
```

Now, I'd like to try it out in the `Trough`. But at the moment, the only way to instantiate a `Trough` object is to do something like this (the numbers are just for demonstrative purposes):
```python
# An example instantiation
trough = Trough(
        acc_params = [0.666, 0.42],
        lag_params = [0.42],
        acc_model_name = "linear",
        lag_model_name = "constant",
)
```

The question is now - how do I use `MyLag` instead of one of the builtins? I'd like to do something like this:
```python
trough = Trough(
        acc_params = [0.666, 0.42],
        acc_model_name = "linear",
        lag_model = MyLag(foo=1.234),  # an instance of a model
)
```

That is, rather than **having** to specify the `lag_params` and the `lag_model_name` we should be able to pass in the `lag_model` directly. Same goes for the accumulation model.

**Review by tmcclintock — CHANGES_REQUESTED** [review]
This looks great so far. It will be *super* helpful to be able to use custom models for everything. One thing I'm worried about is the constructor for `Trough` getting unwieldy - the more arguments we add the more intricate the patterns are just to instantiate the thing.

One thing I think we can do is not have the `custom_X_model` arguments nor the `X_model_name` arguments and instead unify them into one argument called `X_model` with the type of `Union[str, Model]`. Then, rather than having many if/else cases in the method, we can determine what to do based on the type of the argument. Here's what I'm thinking of:
```python
class Trough
    def __init__(
        self,
        acc_model: Union[str, Model],
        acc_params: Optional[List[float]] = None,
        ...
    ):
        ...

        assert isinstance(acc_model, (str, Model)), "acc_model must be str or Model"

        if isinstance(acc_model, str):  # assume we use the model map:
            self.acc_model = ACCUMULATION_MODEL_MAP[acc_model](   
                self.ins_times, self.insolation, *acc_params 
            )
        else:  # it's a custom model
            self.acc_model = acc_model

        # same goes for the lag
```

This makes the API for the `Trough` a bit tighter and do everything we want it to do.

**Review by tmcclintock — APPROVED** [review]

**Comment by tmcclintock** [comment]
Looks great and I have only one more request - can you add two tests in test_troughs.py: 1) with a custom accumulation model passed into the `Trough` and 2) with a custom lag model passed into the `Trough`. Basically, unit tests that are similar to what you are doing in your notebook.

**Comment by kristelizq** [comment]
> Looks great and I have only one more request - can you add two tests in test_troughs.py: 1) with a custom accumulation model passed into the `Trough` and 2) with a custom lag model passed into the `Trough`. Basically, unit tests that are similar to what you are doing in your notebook.

**Comment by kristelizq** [comment]
> Looks great and I have only one more request - can you add two tests in test_troughs.py: 1) with a custom accumulation model passed into the `Trough` and 2) with a custom lag model passed into the `Trough`. Basically, unit tests that are similar to what you are doing in your notebook.

Sure! I also updated the tests for when the input is not a custom model. Pushing the changes soon.

**Comment by tmcclintock** [comment]
Fantastic work @kristelizq. I'm happy to merge this when you think it's ready. Let me know if it's good to go.

**Comment by kristelizq** [comment]
> Fantastic work @kristelizq. I'm happy to merge this when you think it's ready. Let me know if it's good to go.

It is. Thanks!

**Pull request merged**
