### PR TITLE
Prefix of model parameters

### PR DESCRIPTION
**Pull request by kristelizq**
-added a prefix for accumulation classes 'acc_' and a prefix for lag classes 'lag_'
-the parameter_names property uses prefix to assign names of parameters. For example, acc_intercept or lag_intercept
-remove init from subclasses in generic_model file 
-lag and accumulation at times t were modified to include new names of parameters in eval function
-updated tests

### CODE REVIEW

**Comment by kristelizq** [comment]
When using linear accumulation rate and linear lag, the convTest notebook (mcmc) breaks now because the tr.accuModel.parameters.keys and tr.accuModel.parameter_names are the same for both submodels (intercept and slope). I tried using the all_parameters attributes instead but it breaks when I use it in these ways: tr.accuModel.all_parameters or tr.all_parameters. The error reads: 'Linear_Insolation' object has no attribute 'sub_models', for example. This happens after the last commit "Prefix only applies to sub_models now."

**Comment by tmcclintock** [comment]
Thanks for the info. I believe I know the issue. I will add some tests (I thought this pattern was covered with the existing tests, but clearly not) and fix this up this afternoon.

**Comment by tmcclintock** [comment]
@kristelizq this is finally ready for your review. For record keeping, here is a list of what is implemented:

- all `Model` objects now have a `prefix` property that is a string. This prefix is prepended to parameter names if a `model` is used in the `sub_models` list of other models. In our case, all lag models have their parameter names prepended with `"lag_"`. All accumulation models have their parameter names prepended with `"acc_"`. If models don't have a prefix defined and are used as submodels, then an integer index is used (e.g. `"0_constant"`, `"0_constant"`)
- the `Trough` now subclasses `Model`, and the only parameter the trough has is `errorbar`. The accumulation and lag models are added to the `sub_models` list, so their parameters can be referenced correctly:
```python
>>> tr = Trough(acc_model="linear", lag_model="constant", acc_params=[1, 2], lag_params=[3])
>>> tr.all_parameters
{'errorbar': 1.0, 'acc_intercept': 1, 'acc_slope': 2, 'lag_constant': 3}
>>> tr.lagModel.parameters
{'constant': 3}
```
- `Trough.set_model()` has now been refactored (breaking all notebooks XD). It now doesn't need to even know about accumulation or lag models -- all parameters are updated, and then the required retreat splines are updated.

Let me know what you think.

**Comment by kristelizq** [comment]
Beautiful!

**Pull request merged**
